# Generated by Django 6.0.6 on 2026-07-02 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('tech', 'Technical Symposium'), ('non-tech', 'Non-Technical Fest'), ('workshop', 'AI Workshop')], max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
